import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import TransitionHeader from "@/components/TransitionHeader";
import Footer from "@/components/Footer";
import TransitionLayout from "@/components/TransitionLayout";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen w-full flex flex-col
          `}
      >
        <div className="w-full p-4">
          <TransitionHeader />
        </div>
        <div className="w-full flex-1 p-4">
          <div className="max-w-4xl mx-auto">
            <TransitionLayout>{children}</TransitionLayout>
          </div>
        </div>
        <div className="w-full p-4 bg-gray-800">
          <Footer />
        </div>
      </body>
    </html>
  );
}
